// Definición de recursos del sistema
export const RESOURCES = {
  USERS: 'users',
  ROLES: 'roles',
  PRODUCTS: 'products',
  CATEGORIES: 'categories',
  SALES: 'sales',
  CUSTOMERS: 'customers',
  SUPPLIERS: 'suppliers',
  TABLES: 'tables',
  INVENTORY: 'inventory',
  EXPENSES: 'expenses',
  REPORTS: 'reports',
  SETTINGS: 'settings',
  ONLINE_ORDERS: 'online_orders',
} as const

// Definición de acciones disponibles
export const ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  MANAGE: 'manage', // Permiso especial para gestión completa
} as const

// Tipos
export type Resource = (typeof RESOURCES)[keyof typeof RESOURCES]
export type Action = (typeof ACTIONS)[keyof typeof ACTIONS]

// Definición de permisos por rol
export const ROLE_PERMISSIONS = {
  ADMIN: {
    // Administrador tiene acceso completo
    [RESOURCES.USERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.ROLES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.PRODUCTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CATEGORIES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CUSTOMERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.SUPPLIERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.TABLES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.EXPENSES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.REPORTS]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.ONLINE_ORDERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
  },
  MANAGER: {
    // Gerente: puede ver y editar la mayoría, pero no eliminar usuarios ni roles
    [RESOURCES.USERS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.ROLES]: [ACTIONS.READ],
    [RESOURCES.PRODUCTS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CATEGORIES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.SALES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.CUSTOMERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.SUPPLIERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.TABLES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.INVENTORY]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.EXPENSES]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.REPORTS]: [ACTIONS.READ],
    [RESOURCES.SETTINGS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.ONLINE_ORDERS]: [ACTIONS.READ, ACTIONS.UPDATE],
  },
  CASHIER: {
    // Cajero: solo POS y consultas básicas
    [RESOURCES.USERS]: [ACTIONS.READ],
    [RESOURCES.PRODUCTS]: [ACTIONS.READ],
    [RESOURCES.CATEGORIES]: [ACTIONS.READ],
    [RESOURCES.SALES]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.CUSTOMERS]: [ACTIONS.CREATE, ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.TABLES]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.REPORTS]: [ACTIONS.READ],
    [RESOURCES.ONLINE_ORDERS]: [ACTIONS.READ],
  },
  WAITER: {
    // Mesero: tomar órdenes y gestionar mesas
    [RESOURCES.PRODUCTS]: [ACTIONS.READ],
    [RESOURCES.CATEGORIES]: [ACTIONS.READ],
    [RESOURCES.SALES]: [ACTIONS.CREATE, ACTIONS.READ],
    [RESOURCES.CUSTOMERS]: [ACTIONS.READ],
    [RESOURCES.TABLES]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.ONLINE_ORDERS]: [ACTIONS.READ],
  },
  USER: {
    // Usuario básico: solo lectura
    [RESOURCES.PRODUCTS]: [ACTIONS.READ],
    [RESOURCES.CATEGORIES]: [ACTIONS.READ],
  },
} as const

// Tipos de roles
export type RoleName = keyof typeof ROLE_PERMISSIONS

// Lista de roles disponibles
export const ROLES = Object.keys(ROLE_PERMISSIONS) as RoleName[]
